name: BLPhantom_ImageAnalysis
channels:
  - defaults
dependencies:
  - python=3.11.5  # specify your python version
  - numpy
  - tifffile
  - opencv
  - scikit-learn
  - cv2
  - scikit-image
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - jupyter
  - tkinter
  - notebook
  - pillow
  - pip
  # - pip:
      # - some-pip-package # if you need any pip packages that are not available in Conda
